package view.privado.content;


import view.privado.content.VisualPersonaFormulario;
import view.privado.content.Tiquete;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PcIsa
 */
public class VisualSillas extends javax.swing.JFrame {

    /**
     * Creates new form VisualSillas
     */
    Tiquete vi;
    Color colorAnterior;
    public VisualSillas(Tiquete vi) {
        this.vi = vi;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(1);
        colorAnterior = silla1.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        silla1 = new javax.swing.JButton();
        silla2 = new javax.swing.JButton();
        silla3 = new javax.swing.JButton();
        silla4 = new javax.swing.JButton();
        silla5 = new javax.swing.JButton();
        silla6 = new javax.swing.JButton();
        silla7 = new javax.swing.JButton();
        silla8 = new javax.swing.JButton();
        silla16 = new javax.swing.JButton();
        silla9 = new javax.swing.JButton();
        silla10 = new javax.swing.JButton();
        silla11 = new javax.swing.JButton();
        silla12 = new javax.swing.JButton();
        silla13 = new javax.swing.JButton();
        silla14 = new javax.swing.JButton();
        silla15 = new javax.swing.JButton();
        silla23 = new javax.swing.JButton();
        silla18 = new javax.swing.JButton();
        silla19 = new javax.swing.JButton();
        silla20 = new javax.swing.JButton();
        silla21 = new javax.swing.JButton();
        silla17 = new javax.swing.JButton();
        silla22 = new javax.swing.JButton();
        silla24 = new javax.swing.JButton();
        silla25 = new javax.swing.JButton();
        silla26 = new javax.swing.JButton();
        silla27 = new javax.swing.JButton();
        silla28 = new javax.swing.JButton();
        silla29 = new javax.swing.JButton();
        silla30 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        silla1.setText("1");
        silla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla1ActionPerformed(evt);
            }
        });

        silla2.setText("2");
        silla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla2ActionPerformed(evt);
            }
        });

        silla3.setText("3");
        silla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla3ActionPerformed(evt);
            }
        });

        silla4.setText("4");
        silla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla4ActionPerformed(evt);
            }
        });

        silla5.setText("5");
        silla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla5ActionPerformed(evt);
            }
        });

        silla6.setText("6");
        silla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla6ActionPerformed(evt);
            }
        });

        silla7.setText("7");
        silla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla7ActionPerformed(evt);
            }
        });

        silla8.setText("8");
        silla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla8ActionPerformed(evt);
            }
        });

        silla16.setText("16");
        silla16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla16ActionPerformed(evt);
            }
        });

        silla9.setText("9");
        silla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla9ActionPerformed(evt);
            }
        });

        silla10.setText("10");
        silla10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla10ActionPerformed(evt);
            }
        });

        silla11.setText("11");
        silla11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla11ActionPerformed(evt);
            }
        });

        silla12.setText("12");
        silla12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla12ActionPerformed(evt);
            }
        });

        silla13.setText("13");
        silla13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla13ActionPerformed(evt);
            }
        });

        silla14.setText("14");
        silla14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla14ActionPerformed(evt);
            }
        });

        silla15.setText("15");
        silla15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla15ActionPerformed(evt);
            }
        });

        silla23.setText("23");
        silla23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla23ActionPerformed(evt);
            }
        });

        silla18.setText("18");
        silla18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla18ActionPerformed(evt);
            }
        });

        silla19.setText("19");
        silla19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla19ActionPerformed(evt);
            }
        });

        silla20.setText("20");
        silla20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla20ActionPerformed(evt);
            }
        });

        silla21.setText("21");
        silla21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla21ActionPerformed(evt);
            }
        });

        silla17.setText("17");
        silla17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla17ActionPerformed(evt);
            }
        });

        silla22.setText("22");
        silla22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla22ActionPerformed(evt);
            }
        });

        silla24.setText("24");
        silla24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla24ActionPerformed(evt);
            }
        });

        silla25.setText("25");
        silla25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla25ActionPerformed(evt);
            }
        });

        silla26.setText("26");
        silla26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla26ActionPerformed(evt);
            }
        });

        silla27.setText("27");
        silla27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla27ActionPerformed(evt);
            }
        });

        silla28.setText("28");
        silla28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla28ActionPerformed(evt);
            }
        });

        silla29.setText("29");
        silla29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla29ActionPerformed(evt);
            }
        });

        silla30.setText("30");
        silla30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silla30ActionPerformed(evt);
            }
        });

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(silla1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(silla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(silla7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(silla3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(silla5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(silla6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(silla4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(silla8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(silla9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(silla10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(silla13)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(silla14))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(silla11)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(silla12))))
                                        .addGap(6, 6, 6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(silla15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(silla28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(silla29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(silla23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(silla16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(silla18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(silla19, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                        .addComponent(silla17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(silla24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(silla20, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                            .addComponent(silla22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(19, 19, 19)
                                    .addComponent(silla21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(silla26, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(silla27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(silla25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(silla30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(silla1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(silla16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silla17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(silla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(silla3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(silla4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silla19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silla18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(silla5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silla6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(silla20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silla21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(silla7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(silla8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silla22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silla23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(silla25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(silla10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(silla9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(silla24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(silla12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(silla11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(silla27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silla26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(silla14)
                            .addComponent(silla13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(silla29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silla28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(silla30, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silla15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Tiquete().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VisualPersonaFormulario(vi);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void silla30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla30ActionPerformed
        if(vi.viaje.bus.silla.Consultar(29) == true){
            vi.viaje.bus.silla.Asignar(29);
            silla30.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla30ActionPerformed

    private void silla29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla29ActionPerformed
        if(vi.viaje.bus.silla.Consultar(28) == true){
            vi.viaje.bus.silla.Asignar(28);
            silla29.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla29ActionPerformed

    private void silla28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla28ActionPerformed
        if(vi.viaje.bus.silla.Consultar(27) == true){
            vi.viaje.bus.silla.Asignar(27);
            silla28.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla28ActionPerformed

    private void silla27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla27ActionPerformed
        if(vi.viaje.bus.silla.Consultar(26) == true){
            vi.viaje.bus.silla.Asignar(26);
            silla27.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla27ActionPerformed

    private void silla26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla26ActionPerformed
        if(vi.viaje.bus.silla.Consultar(25) == true){
            vi.viaje.bus.silla.Asignar(25);
            silla26.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla26ActionPerformed

    private void silla25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla25ActionPerformed
        if(vi.viaje.bus.silla.Consultar(24) == true){
            vi.viaje.bus.silla.Asignar(24);
            silla25.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla25ActionPerformed

    private void silla24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla24ActionPerformed
        if(vi.viaje.bus.silla.Consultar(23) == true){
            vi.viaje.bus.silla.Asignar(23);
            silla24.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla24ActionPerformed

    private void silla22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla22ActionPerformed
        if(vi.viaje.bus.silla.Consultar(21) == true){
            vi.viaje.bus.silla.Asignar(21);
            silla22.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla22ActionPerformed

    private void silla17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla17ActionPerformed
        if(vi.viaje.bus.silla.Consultar(16) == true){
            vi.viaje.bus.silla.Asignar(16);
            silla17.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla17ActionPerformed

    private void silla21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla21ActionPerformed
        if(vi.viaje.bus.silla.Consultar(20) == true){
            vi.viaje.bus.silla.Asignar(20);
            silla21.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla21ActionPerformed

    private void silla20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla20ActionPerformed
        if(vi.viaje.bus.silla.Consultar(19) == true){
            vi.viaje.bus.silla.Asignar(19);
            silla20.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla20ActionPerformed

    private void silla19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla19ActionPerformed
        if(vi.viaje.bus.silla.Consultar(18) == true){
            vi.viaje.bus.silla.Asignar(18);
            silla19.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla19ActionPerformed

    private void silla18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla18ActionPerformed
        if(vi.viaje.bus.silla.Consultar(17) == true){
            vi.viaje.bus.silla.Asignar(17);
            silla18.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla18ActionPerformed

    private void silla23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla23ActionPerformed
        if(vi.viaje.bus.silla.Consultar(22) == true){
            vi.viaje.bus.silla.Asignar(22);
            silla23.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla23ActionPerformed

    private void silla15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla15ActionPerformed
        if(vi.viaje.bus.silla.Consultar(14) == true){
            vi.viaje.bus.silla.Asignar(14);
            silla15.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla15ActionPerformed

    private void silla14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla14ActionPerformed
        if(vi.viaje.bus.silla.Consultar(13) == true){
            vi.viaje.bus.silla.Asignar(13);
            silla14.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla14ActionPerformed

    private void silla13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla13ActionPerformed
        if(vi.viaje.bus.silla.Consultar(12) == true){
            vi.viaje.bus.silla.Asignar(12);
            silla13.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla13ActionPerformed

    private void silla12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla12ActionPerformed
        if(vi.viaje.bus.silla.Consultar(11) == true){
            vi.viaje.bus.silla.Asignar(11);
            silla12.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla12ActionPerformed

    private void silla11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla11ActionPerformed
        if(vi.viaje.bus.silla.Consultar(10) == true){
            vi.viaje.bus.silla.Asignar(10);
            silla11.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla11ActionPerformed

    private void silla10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla10ActionPerformed
        if(vi.viaje.bus.silla.Consultar(9) == true){
            vi.viaje.bus.silla.Asignar(9);
            silla10.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla10ActionPerformed

    private void silla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla9ActionPerformed
        if(vi.viaje.bus.silla.Consultar(8) == true){
            vi.viaje.bus.silla.Asignar(8);
            silla9.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla9ActionPerformed

    private void silla16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla16ActionPerformed
        if(vi.viaje.bus.silla.Consultar(15) == true){
            vi.viaje.bus.silla.Asignar(15);
            silla16.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla16ActionPerformed

    private void silla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla8ActionPerformed
        if(vi.viaje.bus.silla.Consultar(7) == true){
            vi.viaje.bus.silla.Asignar(7);
            silla8.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla8ActionPerformed

    private void silla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla7ActionPerformed
        if(vi.viaje.bus.silla.Consultar(6) == true){
            vi.viaje.bus.silla.Asignar(6);
            silla7.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla7ActionPerformed

    private void silla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla6ActionPerformed
        if(vi.viaje.bus.silla.Consultar(5) == true){
            vi.viaje.bus.silla.Asignar(5);
            silla6.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla6ActionPerformed

    private void silla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla5ActionPerformed
        if(vi.viaje.bus.silla.Consultar(4) == true){
            vi.viaje.bus.silla.Asignar(4);
            silla5.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla5ActionPerformed

    private void silla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla4ActionPerformed
        if(vi.viaje.bus.silla.Consultar(3) == true){
            vi.viaje.bus.silla.Asignar(3);
            silla4.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla4ActionPerformed

    private void silla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla3ActionPerformed
        if(vi.viaje.bus.silla.Consultar(2) == true){
            vi.viaje.bus.silla.Asignar(2);
            silla3.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla3ActionPerformed

    private void silla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla2ActionPerformed
        if(vi.viaje.bus.silla.Consultar(1) == true){
            vi.viaje.bus.silla.Asignar(1);
            silla2.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla2ActionPerformed

    private void silla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silla1ActionPerformed
        if(vi.viaje.bus.silla.Consultar(0) == true){
            vi.viaje.bus.silla.Asignar(0);
            silla1.setBackground(Color.yellow);
        }else{
            JOptionPane.showMessageDialog(null, "Silla Ocupada, Reserva Otra Silla por favor");
        }
    }//GEN-LAST:event_silla1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton silla1;
    private javax.swing.JButton silla10;
    private javax.swing.JButton silla11;
    private javax.swing.JButton silla12;
    private javax.swing.JButton silla13;
    private javax.swing.JButton silla14;
    private javax.swing.JButton silla15;
    private javax.swing.JButton silla16;
    private javax.swing.JButton silla17;
    private javax.swing.JButton silla18;
    private javax.swing.JButton silla19;
    private javax.swing.JButton silla2;
    private javax.swing.JButton silla20;
    private javax.swing.JButton silla21;
    private javax.swing.JButton silla22;
    private javax.swing.JButton silla23;
    private javax.swing.JButton silla24;
    private javax.swing.JButton silla25;
    private javax.swing.JButton silla26;
    private javax.swing.JButton silla27;
    private javax.swing.JButton silla28;
    private javax.swing.JButton silla29;
    private javax.swing.JButton silla3;
    private javax.swing.JButton silla30;
    private javax.swing.JButton silla4;
    private javax.swing.JButton silla5;
    private javax.swing.JButton silla6;
    private javax.swing.JButton silla7;
    private javax.swing.JButton silla8;
    private javax.swing.JButton silla9;
    // End of variables declaration//GEN-END:variables
}
