/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 05-abr-2013, 20:15:45
 */
package view.publico;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.privado.content.Cliente;



/**
 *
 * @author Administrador
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Menu() {
        initComponents();
        this.setLocation(200, 50);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jMBMENU = new javax.swing.JMenuBar();
        JMARCHIVO = new javax.swing.JMenu();
        JSESSION = new javax.swing.JMenuItem();
        JSALIR = new javax.swing.JMenuItem();
        JMBASICAS = new javax.swing.JMenu();
        JCLIENTE = new javax.swing.JMenuItem();
        JVIAJES = new javax.swing.JMenuItem();
        JBUS = new javax.swing.JMenuItem();
        JMCONSULTAS = new javax.swing.JMenu();
        JRUTACLIENTE = new javax.swing.JMenuItem();
        JRUTA = new javax.swing.JMenuItem();
        JMRESERVA = new javax.swing.JMenu();
        JRESERVACUPO = new javax.swing.JMenuItem();
        JTIQUETE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE RESERVA DE PASAJES PARA EL SERVICIO DE TRANSPORTE VELOCITY COLOMBIA");
        setPreferredSize(new java.awt.Dimension(1000, 650));

        jdpescritorio.setBackground(new java.awt.Color(25, 153, 153));

        JMARCHIVO.setText("Archivo");
        JMARCHIVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMARCHIVOActionPerformed(evt);
            }
        });

        JSESSION.setText("Cerrar Sesion");
        JSESSION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSESSIONActionPerformed(evt);
            }
        });
        JMARCHIVO.add(JSESSION);

        JSALIR.setText("Salir");
        JSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSALIRActionPerformed(evt);
            }
        });
        JMARCHIVO.add(JSALIR);

        jMBMENU.add(JMARCHIVO);

        JMBASICAS.setText("Basicas");
        JMBASICAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMBASICASActionPerformed(evt);
            }
        });

        JCLIENTE.setText("Clientes");
        JCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCLIENTEActionPerformed(evt);
            }
        });
        JMBASICAS.add(JCLIENTE);

        JVIAJES.setText("Viajes");
        JVIAJES.setToolTipText("");
        JVIAJES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVIAJESActionPerformed(evt);
            }
        });
        JMBASICAS.add(JVIAJES);

        JBUS.setText("Bus");
        JMBASICAS.add(JBUS);

        jMBMENU.add(JMBASICAS);

        JMCONSULTAS.setText("Consultas");
        JMCONSULTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCONSULTASActionPerformed(evt);
            }
        });

        JRUTACLIENTE.setText("Rutas Clientes");
        JRUTACLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRUTACLIENTEActionPerformed(evt);
            }
        });
        JMCONSULTAS.add(JRUTACLIENTE);

        JRUTA.setText("Rutas");
        JRUTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRUTAActionPerformed(evt);
            }
        });
        JMCONSULTAS.add(JRUTA);

        jMBMENU.add(JMCONSULTAS);

        JMRESERVA.setText("Reserva");

        JRESERVACUPO.setText("Reserva");
        JMRESERVA.add(JRESERVACUPO);

        JTIQUETE.setText("Tiquete");
        JMRESERVA.add(JTIQUETE);

        jMBMENU.add(JMRESERVA);

        setJMenuBar(jMBMENU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void JMARCHIVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMARCHIVOActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_JMARCHIVOActionPerformed

private void JSESSIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSESSIONActionPerformed
// TODO add your handling code here:
 
   
}//GEN-LAST:event_JSESSIONActionPerformed

private void JSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSALIRActionPerformed
// TODO add your handling code here:
  
}//GEN-LAST:event_JSALIRActionPerformed

private void JCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCLIENTEActionPerformed
// TODO add your handling code here:
    Cliente _fcliente= new Cliente();
    jdpescritorio.add(_fcliente);
    _fcliente.show();
  
    
}//GEN-LAST:event_JCLIENTEActionPerformed

private void JMBASICASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMBASICASActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_JMBASICASActionPerformed

private void JVIAJESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVIAJESActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_JVIAJESActionPerformed

    private void JMCONSULTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCONSULTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMCONSULTASActionPerformed

    private void JRUTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRUTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRUTAActionPerformed

    private void JRUTACLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRUTACLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRUTACLIENTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JBUS;
    private javax.swing.JMenuItem JCLIENTE;
    private javax.swing.JMenu JMARCHIVO;
    private javax.swing.JMenu JMBASICAS;
    private javax.swing.JMenu JMCONSULTAS;
    private javax.swing.JMenu JMRESERVA;
    private javax.swing.JMenuItem JRESERVACUPO;
    private javax.swing.JMenuItem JRUTA;
    private javax.swing.JMenuItem JRUTACLIENTE;
    private javax.swing.JMenuItem JSALIR;
    private javax.swing.JMenuItem JSESSION;
    private javax.swing.JMenuItem JTIQUETE;
    private javax.swing.JMenuItem JVIAJES;
    private javax.swing.JMenuBar jMBMENU;
    public static javax.swing.JDesktopPane jdpescritorio;
    // End of variables declaration//GEN-END:variables
}
